using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Events;

public class Timer : MonoBehaviour
{
    [SerializeField]
    Text TimerText;
    [SerializeField]
    float _minutes = 1;
    [SerializeField]
    float _limitTime = 00;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField]
    bool _isStop = false;
    
    [SerializeField] private UnityEvent onTimerFinished;
    
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        //Debug.Log($"{_minutes}:{_limitTime}");//$ï¿½}ï¿½[ï¿½N+""ï¿½Ì’ï¿½ï¿½Å–ï¿½ï¿½ßï¿½ï¿½İ‚É‚È‚ï¿½
        if (!_isStop) { _limitTime -= Time.deltaTime; }//isStopï¿½ï¿½elseï¿½Ìï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½Atrueï¿½Ìï¿½ï¿½ï¿½ß‚ï¿½
        if (_limitTime < 0 && _minutes != 0)//ï¿½ê•ªï¿½Èï¿½cï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç‚µï¿½Ä•bï¿½ï¿½ï¿½ï¿½59ï¿½bï¿½É‚ï¿½ï¿½ï¿½
        {
            _minutes--;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½1ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            _limitTime = 59.99f;
        }
        else if (_limitTime < 0 && _minutes == 0)//ï¿½ê•ªï¿½ï¿½ï¿½cï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Í•bï¿½ï¿½ï¿½ï¿½0ï¿½É‚ï¿½ï¿½ï¿½
        {
            Debug.Log("Finish!");
            _isStop = true;
            _limitTime = 0;
            onTimerFinished?.Invoke();
        }

        TimerText.text = _minutes.ToString("00") + ":"+ ((int)_limitTime).ToString("00");//ï¿½cï¿½èï¿½Ô‚ğ®ï¿½ï¿½Å•\ï¿½ï¿½
    }
}
